import { Toaster } from "@/components/ui/toaster";
import { PropsWithChildren, Suspense } from "react";
import "three-dots/dist/three-dots.css";
import "./globals.css";
import { Icons } from "@/components/ui/icons";
import TRPC_Provider from "./_trpc/TRPC_Provider";
//import { trpc } from "@/utils/trpc";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LoadingShip = () => {
  return (
    <div className="flex justify-center items-center h-full">
      <Icons.spinner className="mr-2 h-48 w-48 animate-spin" />
    </div>
  );
};

async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <TRPC_Provider>
          <Toaster />
          <main className="w-full grow bg-background flex flex-col items-center h-[calc(100%-5rem)]">
            <Suspense fallback={<LoadingShip />}>{children}</Suspense>
          </main>
        </TRPC_Provider>
      </body>
    </html>
  );
}

export default RootLayout;
